# Install extension: REST Client 

### USER
# Get
GET http://localhost:5000/odata/users
Accept: application/json;
###

# Create
POST http://localhost:5000/odata/users
Content-Type: application/json

{
  "FullName": "abc"
}
###

# GET by id
GET http://localhost:5000/odata/users(3)
Accept: application/json;
###

# Update
PATCH http://localhost:5000/odata/users(3)
Content-Type: application/json

{
  "FullName": "edited {{$datetime "DD/MM/YYYY HH:mm:ss" 7 h}}"
}

### PRODUCT
# Get
GET http://localhost:5000/odata/products?$filter=contains(Name, 'X')&$expand=ProductDetails&$top=2&skip=0&$count=true
Accept: application/json;
###

# Create
POST http://localhost:5000/odata/products
Content-Type: application/json

{
  "Name": "iphone X",
  "ProductDetails": [
    {
      "Desc": "12GB"
    },
    
    {
      "Desc": "64GB"
    }
  ]
}
###

# GET by id
GET http://localhost:5000/odata/products(1)
Accept: application/json;
###

# Update
PATCH http://localhost:5000/odata/products(1)
Content-Type: application/json

{
  "Name": "edited {{$datetime "DD/MM/YYYY HH:mm:ss" 7 h}}"
}


